language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - node_modules
install: npm install
script: bash ./deploy/test.sh
jobs:
  include:
    - stage: build
      node_js: "6"
      script: bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "af862fa96d3e"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
